# Generated by Django 5.2.5 on 2025-10-23 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_education_profile_github_link_and_more'),
        ('profiles', '0002_application_applicant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='accounts.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
    ]
