# Generated by Django 5.0 on 2025-09-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('skills', models.TextField()),
                ('location', models.TextField()),
                ('salaryRange', models.TextField()),
                ('remote', models.TextField()),
                ('visaSponsorship', models.TextField()),
            ],
        ),
    ]
