# Generated by Django 5.2.5 on 2025-09-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
