# Generated by Django 5.2.5 on 2025-10-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
