# Generated by Django 5.0 on 2025-11-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_delete_role'),
        ('profiles', '0002_alter_application_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
