# Generated by Django 5.0 on 2025-10-26 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("recruiters", "Recruiters only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("candidate", "Job Seeker"),
                            ("recruiter", "Recruiter"),
                        ],
                        default="candidate",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Company name (if you are a recruiter)",
                        max_length=100,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Professional headline or title",
                        max_length=200,
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True,
                        help_text="List your skills (one per line or comma-separated)",
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True,
                        help_text="Educational background and qualifications",
                    ),
                ),
                (
                    "work_experience",
                    models.TextField(
                        blank=True, help_text="Work experience and professional history"
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to your portfolio or personal website",
                    ),
                ),
                (
                    "linkedin_link",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "github_link",
                    models.URLField(blank=True, help_text="GitHub profile URL"),
                ),
                (
                    "other_links",
                    models.TextField(
                        blank=True, help_text="Other relevant links (one per line)"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
