# Generated by Django 5.0 on 2025-09-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.TextField(
                blank=True, help_text="Educational background and qualifications"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="github_link",
            field=models.URLField(blank=True, help_text="GitHub profile URL"),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(
                blank=True, help_text="Professional headline or title", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_link",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
        migrations.AddField(
            model_name="profile",
            name="other_links",
            field=models.TextField(
                blank=True, help_text="Other relevant links (one per line)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolio_link",
            field=models.URLField(
                blank=True, help_text="Link to your portfolio or personal website"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="List your skills (one per line or comma-separated)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_experience",
            field=models.TextField(
                blank=True, help_text="Work experience and professional history"
            ),
        ),
    ]
